rowvector1 = 3:3:15;
rowvector2 = -4:0.5:4;
rowvector3 = 0:pi/6:3*pi;
l1 =(length(rowvector1));
l2 =(length(rowvector2));
l3 =(length(rowvector3));
disp ('length of rowvector1');
disp(l1);
disp ('length of rowvector2');
disp(l2);
disp ('length of rowvector3');
disp(l3);
disp('first element of rowvector1');
disp(rowvector1(1));
disp('last element of rowvector1');
disp(rowvector1(end));
disp('first element of rowvector2');
disp(rowvector2(1));
disp('last element of rowvector2');
disp(rowvector2(end));
disp('first element of rowvector3');
disp(rowvector3(1));
disp('last element of rowvector3');
disp(rowvector3(end));
disp('last three elements of rowvector1');
disp(rowvector1((end-2): end));
disp('last three elements of rowvector2');
disp(rowvector2((end-2):end));
disp('last three elements of rowvector3');
disp(rowvector3((end-2):end));
